#!/bin/sh
set -ex

# This file takes an sqlite3 database generated by https://bupstash.io
# and then attempts to enable cksumvfs, this produces an error.

CC=${CC:-gcc}

if ! test -e sqlite3-shell
then
  $CC shell.c sqlite3.c -ldl -lpthread -o sqlite3-shell
fi
if ! test -e cksumvfs.so
then
  $CC -fPIC -shared cksumvfs.c -o cksumvfs.so
fi

cp backup.sendlog backup.copy.sendlog

# Vacuum works fine initially, integrity checks pass.
./sqlite3-shell <<EOF
.open backup.copy.sendlog
vacuum;
vacuum;
pragma integrity_check;
EOF

# Enable cksumvfs following sqlite website.
# Second vacuum fails with failed checksum.
./sqlite3-shell <<EOF
.load ./cksumvfs.so
.open backup.copy.sendlog
.filectrl reserve_bytes 8
vacuum;
vacuum;
EOF
